server:
  port: "3000"
database:
  host: "192.168.1.129"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "ktrlplane"
  graphpath: "ktrlplane_graph"
  sslmode: "disable"
auth0:
  domain: "YOUR_AUTH0_DOMAIN.auth0.com"
  audience: "YOUR_API_AUDIENCE"
