server:
  port: "3001"
database:
  host: "192.168.1.129"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "ktrlplane"
  graphpath: "ktrlplane_graph"
  sslmode: "disable"
auth0:
  domain: "auth.konnektr.io"
  audience: "https://api.ktrlplane.konnektr.io"
  client_id: "ObWW1A2syc8tFeYkxTwnRvRdNgbuP9BE"
